-- -------- CREACIÓN DE BASE -----------------

DROP SCHEMA IF EXISTS ferreteria3Hermanos;
CREATE SCHEMA ferreteria3Hermanos;
USE ferreteria3Hermanos;

-- -------- CREACIÓN DE TABLAS -----------------

CREATE TABLE IF NOT EXISTS proveedores(
  COD_EMP INT NOT NULL UNIQUE
, LIS_EMP INT NOT NULL UNIQUE AUTO_INCREMENT
, NOM_EMP VARCHAR(25) NOT NULL UNIQUE
, DIR_EMP VARCHAR(50) NOT NULL UNIQUE
, TEL_EMP INT NOT NULL UNIQUE
, NOM_VEN VARCHAR(25)
, TEL_VEN INT
, TIEMPO DATETIME
, CONSTRAINT PK_COD_EMP PRIMARY KEY (COD_EMP)
);

CREATE TABLE IF NOT EXISTS listas_proveedores(
  LIS_EMP INT NOT NULL UNIQUE AUTO_INCREMENT
, COD_EMP INT NOT NULL UNIQUE
, COD_PRO INT NOT NULL UNIQUE
, VAL_COS DOUBLE NOT NULL
, TIEMPO DATETIME
, CONSTRAINT PK_LIS_EMP PRIMARY KEY (LIS_EMP)
);

CREATE TABLE IF NOT EXISTS decripcion_productos(
  COD_PRO INT NOT NULL UNIQUE AUTO_INCREMENT
, NOM_PRO VARCHAR(25) NOT NULL
, DES_PRO VARCHAR(100) DEFAULT "Sin informacion"
, PRE_PRO VARCHAR(10) DEFAULT "Unidad"
, TIEMPO DATETIME
, CONSTRAINT PK_COD_PRO PRIMARY KEY (COD_PRO)
);

CREATE TABLE IF NOT EXISTS producto_por_proveedor(
  PRO_PRO INT NOT NULL UNIQUE AUTO_INCREMENT
, LIS_EMP INT NOT NULL UNIQUE
, COD_PRO INT NOT NULL UNIQUE
, VAL_COS DOUBLE NOT NULL
, VAL_UNI DOUBLE NOT NULL
, TIEMPO DATETIME
, CONSTRAINT PK_PRO_PRO PRIMARY KEY (PRO_PRO)
);

CREATE TABLE IF NOT EXISTS clientes(
  ID_CLI INT(11) NOT NULL UNIQUE AUTO_INCREMENT
, APE_CLI VARCHAR(25)
, NOM_CLI VARCHAR(25) NOT NULL
, DIR_CLI VARCHAR(50)
, TEL_CLI INT UNIQUE
, CON_TRI VARCHAR(25)
, NAC DATE
, TIEMPO DATETIME
, CONSTRAINT PK_ID_CLI PRIMARY KEY (ID_CLI)
);

CREATE TABLE IF NOT EXISTS factura_compra(
  FAC_CPA INT NOT NULL UNIQUE
, COD_EMP INT NOT NULL UNIQUE
, VAL_CPA DOUBLE NOT NULL
, TIEMPO DATETIME
, CONSTRAINT PK_FAC_CPA PRIMARY KEY (FAC_CPA)
);

CREATE TABLE IF NOT EXISTS detalle_compra(
  PRO_CPA INT NOT NULL UNIQUE
, PRO_PRO INT NOT NULL UNIQUE
, CAN_PRO INT NOT NULL
, FAC_CPA INT NOT NULL UNIQUE
, TIEMPO DATETIME
-- , CONSTRAINT PK_PRO_CPA PRIMARY KEY (PRO_CPA) Se define como PK concatenada en el alter
);

CREATE TABLE IF NOT EXISTS factura_venta(
  FAC_VTA INT NOT NULL UNIQUE AUTO_INCREMENT
, ID_CLI INT NOT NULL UNIQUE
, VAL_VTA DOUBLE NOT NULL
, TIEMPO DATETIME
, CONSTRAINT PK_FAC_CPA PRIMARY KEY (FAC_VTA)
);

CREATE TABLE IF NOT EXISTS detalle_venta(
  PRO_VTA INT NOT NULL UNIQUE
, PRO_PRO INT NOT NULL UNIQUE
, CAN_PRO INT NOT NULL
, FAC_VTA INT NOT NULL UNIQUE
, TIEMPO DATETIME
-- , CONSTRAINT PK_PRO_VTA PRIMARY KEY (PRO_VTA) Se define como PK concatenada en el alter
);

CREATE TABLE IF NOT EXISTS stock(
  PRO_STO INT NOT NULL UNIQUE
, PRO_PRO INT NOT NULL UNIQUE
, CAN_PRO INT NOT NULL
, TIEMPO DATETIME
-- , CONSTRAINT PK_PRO_STO PRIMARY KEY (PRO_STO) Se define en el Alter ya que será concatenada tomando una FK
);

-- -------- DEFINICIÓN DE FK Y CONCATENADAS MEDIANTE ALTER -----------------

ALTER TABLE proveedores ADD CONSTRAINT FK_proveedores_listasPro FOREIGN KEY FK_proveedores_listaPro(LIS_EMP)
REFERENCES listas_proveedores (LIS_EMP);

ALTER TABLE listas_proveedores ADD CONSTRAINT FK_listasPro_proveedores FOREIGN KEY FK_listaPro_proveedores(COD_EMP)
REFERENCES proveedores (COD_EMP);


ALTER TABLE producto_por_proveedor ADD CONSTRAINT FK_productoPorPro_listasPro FOREIGN KEY FK_productoPorPro_listasPro(LIS_EMP)
REFERENCES proveedores (LIS_EMP),
ADD CONSTRAINT FK_productoPorPro_decripcionPro FOREIGN KEY FK_productoPorPro_decripcionPro(COD_PRO)
REFERENCES decripcion_productos (COD_PRO);


ALTER TABLE factura_compra ADD CONSTRAINT FK_facturaCpa_proveedores FOREIGN KEY FK_facturaCpa_proveedores(COD_EMP)
REFERENCES proveedores (COD_EMP);

ALTER TABLE detalle_compra ADD CONSTRAINT FK_detalleCpa_facturaCpa FOREIGN KEY FK_detalleCpa_facturaCpa(FAC_CPA)
REFERENCES factura_compra (FAC_CPA),
ADD CONSTRAINT FK_detalleCpa_productoPorPro FOREIGN KEY FK_detalleCpa_productoPorPro(PRO_PRO)
REFERENCES producto_por_proveedor (PRO_PRO),
ADD CONSTRAINT PK_PRO_CPA PRIMARY KEY (PRO_PRO, CAN_PRO); -- CONCATENADA;


ALTER TABLE factura_venta ADD CONSTRAINT FK_facturaVta_clientes FOREIGN KEY FK_facturaVta_clientes(ID_CLI)
REFERENCES clientes (ID_CLI);

ALTER TABLE detalle_venta ADD CONSTRAINT FK_detalleVta_facturaVta FOREIGN KEY FK_detalleVta_facturaVta(FAC_VTA)
REFERENCES factura_venta (FAC_VTA),
ADD CONSTRAINT FK_detalleVta_productoPorPro FOREIGN KEY FK_detalleVta_productoPorPro(PRO_PRO)
REFERENCES producto_por_proveedor (PRO_PRO),
ADD CONSTRAINT PK_PRO_VTA PRIMARY KEY (PRO_PRO, CAN_PRO); -- CONCATENADA;
;

ALTER TABLE stock ADD CONSTRAINT FK_stock_productoPorPro FOREIGN KEY FK_stock_productoPorPro(PRO_PRO)
REFERENCES producto_por_proveedor (PRO_PRO),
ADD CONSTRAINT PK_PRO_STO PRIMARY KEY (PRO_PRO, CAN_PRO); -- CONCATENADA
