-- -------- CREACIÓN DE BASE -----------------

DROP SCHEMA IF EXISTS ferreteria3Hermanos;
CREATE SCHEMA ferreteria3Hermanos;
USE ferreteria3Hermanos;

-- -------- CREACIÓN DE TABLAS -----------------

-- drop table if exists proveedores;
CREATE TABLE IF NOT EXISTS proveedores(
  ID_PROV INT NOT NULL AUTO_INCREMENT,
  CUIT_PROV VARCHAR(20),
  NOMBRE_PROV VARCHAR(25) NOT NULL,
  DIREC_PROV VARCHAR(50) NOT NULL,
  TEL_PROV VARCHAR(20) NOT NULL UNIQUE,
  PRIMARY KEY (ID_PROV)
);

-- drop table if exists descripcion_productos;
CREATE TABLE IF NOT EXISTS descripcion_productos(
  COD_PRO INT NOT NULL AUTO_INCREMENT,
  NOMBRE_PRO VARCHAR(25) NOT NULL,
  DESCR_PRO VARCHAR(100) DEFAULT "Sin información",
  TIEMPO DATETIME,
  PRIMARY KEY (COD_PRO)
);

-- drop table if exists producto_por_proveedor;
CREATE TABLE IF NOT EXISTS producto_por_proveedor(
  ID_PROV INT NOT NULL,
  COD_PRO INT NOT NULL,
  VAL_COS DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  VAL_VTA DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  TIEMPO DATETIME,
  PRIMARY KEY (ID_PROV, COD_PRO),
  FOREIGN KEY (ID_PROV) REFERENCES proveedores(ID_PROV),
  FOREIGN KEY (COD_PRO) REFERENCES descripcion_productos(COD_PRO)
);

-- drop table if exists clientes;
CREATE TABLE IF NOT EXISTS clientes(
  ID_CLI INT NOT NULL AUTO_INCREMENT,
  APE_CLI VARCHAR(25) NOT NULL,
  NOM_CLI VARCHAR(25) NOT NULL,
  DIR_CLI VARCHAR(50) NOT NULL,
  TEL_CLI VARCHAR(20) NOT NULL,
  CON_TRI VARCHAR(25),
  NAC DATE,
  TIEMPO DATETIME,
  PRIMARY KEY (ID_CLI)
);

-- drop table if exists factura_compra;
CREATE TABLE IF NOT EXISTS factura_compra(
  FAC_CPA INT NOT NULL AUTO_INCREMENT,
  ID_PROV INT NOT NULL,
  TIEMPO DATETIME,
  PRIMARY KEY (FAC_CPA),
  FOREIGN KEY (ID_PROV) REFERENCES proveedores(ID_PROV)
);

-- drop table if exists detalle_compra;
CREATE TABLE IF NOT EXISTS detalle_compra(
  FAC_CPA INT NOT NULL,
  COD_PRO INT NOT NULL,
  CAN_PRO INT NOT NULL,
  VAL_CPA DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  TIEMPO DATETIME,
  PRIMARY KEY (FAC_CPA, COD_PRO),
  FOREIGN KEY (FAC_CPA) REFERENCES factura_compra(FAC_CPA),
  FOREIGN KEY (COD_PRO) REFERENCES descripcion_productos(COD_PRO)
);

-- drop table if exists factura_venta;
CREATE TABLE IF NOT EXISTS factura_venta(
  FAC_VTA INT NOT NULL AUTO_INCREMENT,
  ID_CLI INT NOT NULL,
  TIEMPO DATETIME,
  PRIMARY KEY (FAC_VTA),
  FOREIGN KEY (ID_CLI) REFERENCES clientes(ID_CLI)
);

-- drop table if exists detalle_venta;
CREATE TABLE IF NOT EXISTS detalle_venta(
  FAC_VTA INT NOT NULL,
  COD_PRO INT NOT NULL,
  CAN_PRO INT NOT NULL,
  VAL_VTA DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  TIEMPO DATETIME,
  PRIMARY KEY (FAC_VTA, COD_PRO),
  FOREIGN KEY (FAC_VTA) REFERENCES factura_venta(FAC_VTA),
  FOREIGN KEY (COD_PRO) REFERENCES descripcion_productos(COD_PRO)
);

-- drop table if exists stock;
CREATE TABLE IF NOT EXISTS stock(
  COD_PRO INT NOT NULL,
  CAN_PRO INT NOT NULL,
  TIEMPO DATETIME,
  PRIMARY KEY (COD_PRO),
  FOREIGN KEY (COD_PRO) REFERENCES descripcion_productos(COD_PRO)
);
